"""
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
import math

def numDiv(n):
    c = 0
    upp = int(math.sqrt(n)+1)   # Only need to go until sqrt n + 1
    for i in range(1,upp):
        if (n%i==0):            # Check if divisor
            if (n/i==i):
                c = c + 1       # Case where divisors are equal
            else:
                c = c + 2       # If it is sqrt n, divisor has pair

    return c

i = 0; tri = 0; div = 0
# Loop with exit condition of 500 divisors
while div < 500:
    i = i + 1
    tri = i + tri
    div = numDiv(tri)

print(tri)