"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
import math
# (sqrt(8x+1)-1) % 2 == 0
def istriangular(x):
    if (math.sqrt(8*x+1)-1) % 2 == 0:
        return True
    else:
        return False

def ispent(x):
    if (math.sqrt(24*x+1)+1) % 6 == 0:
        return True
    else:
        return False



hx = 144
not_found = True
while not_found:
    hx += 1
    hex = hx*(2*hx-1)
    # Check if number is triangular and pentagonal
    if istriangular(hex) == True and ispent(hex) == True:
        print(hex)
        not_found = False
