"""
Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
Triangle 	  	P3,n=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Square 	  	P4,n=n2 	  	1, 4, 9, 16, 25, ...
Pentagonal 	  	P5,n=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	P6,n=n(2n−1) 	  	1, 6, 15, 28, 45, ...
Heptagonal 	  	P7,n=n(5n−3)/2 	  	1, 7, 18, 34, 55, ...
Octagonal 	  	P8,n=n(3n−2) 	  	1, 8, 21, 40, 65, ...

The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

    The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
    Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
    This is the only set of 4-digit numbers with this property.

Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.
"""

tri_l = []
n = 1
tri = 0
while tri < 1e4:
    tri = n*(n+1)/2
    if tri > 999:
        tri_l.append(str(int(tri)))
    n += 1
    
squ_l = []
n = 1
squ = 0
while squ < 1e4:
    squ = n**2
    if squ > 999:
        squ_l.append(str(int(squ)))
    n += 1
    
pen_l = []
n = 1
pen = 0
while pen < 1e4:
    pen = n*(3*n-1)/2
    if pen > 999:
        pen_l.append(str(int(pen)))
    n += 1
    
hex_l = []
n = 1
hex = 0
while hex < 1e4:
    hex = n*(2*n-1)
    if hex > 999:
        hex_l.append(str(int(hex)))
    n += 1
    
hep_l = []
n = 1
hep = 0
while hep < 1e4:
    hep = n*(5*n-3)/2
    if hep > 999:
        hep_l.append(str(int(hep)))
    n += 1

oct_l = []
n = 1
oct = 0
while oct < 1e4:
    oct = n*(3*n-2)
    if oct > 999:
        oct_l.append(str(int(oct)))
    n += 1
    
tots = [tri_l,squ_l,pen_l,hex_l,hep_l,oct_l]

def findcyc(lst,rem,ref,cyc):
    if len(cyc[-1]) == 4 and cyc[0][0:2] == cyc[-1][2:]:
        return cyc
    for n in lst:
        if len(cyc[-1]) == 4 and cyc[0][0:2] == cyc[-1][2:]:
            return cyc
        n_end = n[2:]
        cyc[len(rem)-1] = n
        for r in ref:
            if r not in rem:
                n_lst = []
                for x in tots[r]:
                    if n_end == x[0:2]:
                        n_lst.append(x)
                if len(n_lst) > 0:
                    findcyc(n_lst,rem+[r],ref,cyc)
                    
cyc = findcyc(oct_l,[5],[0,1,2,3,4,5],['0','0','0','0','0','0'])
sum = 0
for c in cyc:
    sum += int(c)

print(sum)
